BSA_WebSite/BSA_WebSite/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='/home/', permanent=True)),
    url(r'^login/$', RedirectView.as_view(url='/home/login', permanent=True)),
    url(r'^home/', include('MainSite.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

BSA_WebSite/MainSite/urls.py
from django.conf.urls import url

from . import views

app_name = 'mainsite'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^people/$', views.people, name='people'),
    url(r'^events/$', views.events, name='events'),
    url(r'^gallery/$', views.gallery, name='gallery'),
    url(r'^live/$', views.live, name='live'),
]

BSA_WebSite/MainSite/models.py
from django.db import models

# Create your models here.
STATIC_DIR = 'static'
TEAMS = (
    ('', 'None'),
    ('Athletics (Men)', 'Athletics (Men)'),
    ('Athletics (Women)', 'Athletics (Women)'),
    ('Aquatics (Men)', 'Aquatics (Men)'),
    ('Aquatics (Women)', 'Aquatics (Women)'),
    ('Badminton (Men)', 'Badminton (Men)'),
    ('Badminton (Women)', 'Badminton (Women)'),
    ('Basketball (Men)', 'Basketball (Men)'),
    ('Basketball (Women)', 'Basketball (Women)'),
    ('Cricket', 'Cricket'),
    ('Football', 'Football'),
    ('Hockey', 'Hockey'),
    ('Lawn Tennis (Men)', 'Lawn Tennis (Men)'),
    ('Lawn Tennis (Women)', 'Lawn Tennis (Women)'),
    ('Squash', 'Squash'),
    ('Table Tennis (Men)', 'Table Tennis (Men)'),
    ('Table Tennis (Women)', 'Table Tennis (Women)'),
    ('Volleyball (Men)', 'Volleyball (Men)'),
    ('Volleyball (Women)', 'Volleyball (Women)'),
    ('Weight-lifting', 'Weight-lifting')
)


class People(models.Model):
    Secretary = 'secy'
    Executive = 'exe'
    Faculty = 'fac'
    Captain = 'cap'
    ViceCaptain = 'vicecap'
    people_types = (
        (Secretary, 'Secretary'),
        (Executive, 'Executive'),
        (Faculty, 'Faculty'),
        (Captain, 'Captain'),
        (ViceCaptain, 'Vice-Captain')
    )
    type = models.CharField(blank=False, max_length=8, choices=people_types, default=Secretary)
    team = models.CharField(blank=True, max_length=20, choices=TEAMS, default='', help_text="Leave blank if not capn or vice-capn")
    name = models.CharField(blank=False, max_length=30, help_text="Full Name")
    entryno = models.CharField(blank=True, max_length=15, help_text="Leave Blank if faculty")
    mobileno = models.CharField(blank=True, max_length=15, help_text="Mobile Number")
    email = models.CharField(blank=False, max_length=30, help_text="Email ID")
    hostel = models.CharField(blank=True, max_length=15, help_text="Leave Blank if faculty")
    fb = models.CharField(blank=True, max_length=200, help_text="Not required")
    image_link = models.CharField(blank=False, max_length=500)


class Event(models.Model):
    name = models.CharField(blank=False, max_length=50)
    date = models.DateField(blank=False)
    time = models.TimeField(blank=True)
    short_des = models.CharField(blank=True, max_length=300)
    long_des = models.CharField(blank=True, max_length=2000)
    logo_link = models.CharField(blank=True, max_length=500)
    image_link = models.CharField(blank=True, max_length=500)


class Gallery(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    path_to_images = models.CharField(blank=False, max_length=500)


class Announcement(models.Model):
    desc = models.CharField(blank=False, max_length=300)
    link = models.CharField(blank=True, max_length=500)


class LiveMatch(models.Model):
    score = models.CharField(blank=False, max_length=100)
    start_time = models.DateTimeField('time started')
    duration = models.TimeField
    header = models.CharField(blank=False, max_length=500)
    end_text = models.CharField(blank=True, max_length=500)


class Comment(models.Model):
    LiveMatch = models.ForeignKey(LiveMatch, on_delete=models.CASCADE)
    text = models.CharField(max_length=300)
    timestamp = models.DateTimeField(auto_now_add=True)

BSA_WebSite/MainSite/views.py
from django.shortcuts import render
from django.http import HttpResponse
from datetime import datetime, timedelta
from .models import People, Event, Gallery, Announcement, LiveMatch, Comment
import os
# Create your views here.

"""DECLARE LINK TO STATIC DISPLAY IMAGES HERE"""
STATIC_DIR = 'static'
SHOWCASE_DIR = 'showcase'
""" END"""

Secretary = 'secy'
Executive = 'exe'
Faculty = 'fac'
Captain = 'cap'
ViceCaptain = 'vicecap'
MAX_RECENT_MATCHES = 5


def index(request):
    announcements = Announcement.objects.all()
    live_matches = []
    upcoming_matches = []
    for match in LiveMatch.objects.all():
        if match.start_time > datetime.now() - match.duration:
            live_matches.append(match)
        elif match.start_time > datetime.now():
            upcoming_matches.append(match)
    context = {'announcements': announcements, 'live_matches': live_matches, 'upcoming_matches': upcoming_matches}
    return render(request, 'MainSite/index.html', context)


def people(request):
    faculty_list = People.objects.filter(type=Faculty)
    secretaries = People.objects.filter(type=Secretary)
    executives = People.objects.filter(type=Executive)
    team_members = People.objects.filter(type=Captain or ViceCaptain).order_by('team')
    context = {'faculty_list': faculty_list, 'secretaries': secretaries, 'executives': executives,
               'team_members': team_members}
    return render(request, 'MainSite/people.html', context)


def events(request):
    date = datetime.today()
    day_events = Event.objects.filter(date=date)
    past_events = Event.objects.filter(date__lt=date).order_by("-date")
    upcoming_events = Event.objects.filter(date__gt=date).order_by("date")
    context = {'day_events': day_events, 'past_events': past_events, 'upcoming_events': upcoming_events}
    return render(request, 'MainSite/events.htmL', context)


def gallery(request):
    all_event_images = []
    showcase_images = []
    for root, dirs, files in os.walk(os.path.join(STATIC_DIR, SHOWCASE_DIR)):
        for filename in files:
            showcase_images.append(filename)
    showcase = {
        "base_dir": SHOWCASE_DIR,
        "images": showcase_images
    }
    for item in Gallery.objects.all():
        images = []
        for root, dirs, files in os.walk(os.path.join(STATIC_DIR, item.path_to_images)):
            for filename in files:
                images.append(filename)
        event = {
            "event_name": item.event.name,
            "base_dir": item.path_to_images,
            "images": images
        }
        all_event_images.append(event)
    return render(request, 'MainSite/gallery.htmL', {'all_event_images': all_event_images, 'showcase': showcase,
                                                     "static_dir": STATIC_DIR})


def live(request):
    live_matches = []
    temp = []
    upcoming_matches = []
    for match in LiveMatch.objects.all():
        if match.start_time > datetime.now() - match.duration:
            live_matches.append(match)
        elif match.start_time > datetime.now():
            upcoming_matches.append(match)
        else:
            temp.append()
    comments = {}
    for match in live_matches:
        comments[match.header] = match.comment_set.all()
    recent_matches = []
    for match in temp:
        if match.start_time > datetime.now() - timedelta(days=7):
            recent_matches.append(match)
    context = {'upcoming_matches': upcoming_matches, 'live_matches': live_matches, 'recent_matches': recent_matches, 'comments': comments}
    return render(request, 'MainSite/live.htmL', context)

BSA_WebSite/MainSite/templates/MainSite/events.html
{% extends 'base.html' %}
{% load static %}
{% block privatestyles %}
    <link  href="{% static 'MainSite/timeline.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'MainSite/events.css' %}" type="text/css">
{% endblock privatestyles %}
{% block privatejs %}
    <script src="{% static "MainSite/js/jquery.tabslet.min.js" %}" type="text/javascript"></script>
    <script src="{% static "MainSite/js/wow.min.js" %}" type="text/javascript"></script>
{% endblock privatejs %}
{% block body %}
    <script>
    new WOW().init();
    </script>
{% if day_events %}
    <h1 align="center"> TODAY !!</h1>
    <div class="container">
    {% for event in day_events %}

<center>
<div id="contactsb" style="display: inline-block;">
<img src="{{ event.image_link }}" alt="Image for event" id="contactbg" />

<img src="{{ event.logo_link }}" alt="Logo for event" id="contactpropic" />

<span id="sbtexcon">
    <br/>
{{ event.long_des }}
<div class="sbshbor">
{{ event.time }}    {{ event.date }}
</div>
</div>
</center>

    {% endfor %}
    </div>
{% endif %}
<div class='tabs' data-toggle="tabslet" style="margin-top: 1%">
	<ul class="container" style="text-align: center">
		<li style="display: inline; background: #adadad; margin: 2px; padding: 5px"><a href="#tab-1">Upcoming Events</a></li>
		<li style="display: inline; background: #adadad; margin: 2px; padding: 5px"><a href="#tab-2">Past Events</a></li>
	</ul>
	<div id='tab-1'>
<section id=timeline>
	<h1>Upcoming Events</h1>
	<p class="leader">Some caption</p>
	<div class="demo-card-wrapper">
        {% for event in upcoming_events %}
		<div class="demo-card demo-card--step{{ forloop.counter }}">
			<div class="head">
				<div class="number-box">
					<span><img src="{{ event.logo_link }}" height="50px" width="50px" alt="logo"></span>
				</div>
				<h2><span class="small">{{ event.date }}</span>{{ event.name }}</h2>
			</div>
			<div class="body">
				<p>{{ event.short_des }}</p>
				<img src="{{ event.image_link }}" alt="Image for event">
			</div>
		</div>
        {% endfor %}
	</div>
</section>
    </div>
	<div id='tab-2'>
    <section id=timeline>
	<h1>Past Events</h1>
	<p class="leader">Some caption</p>
	<div class="demo-card-wrapper">
        {% for event in past_events %}
		<div class="demo-card demo-card--step{{ forloop.counter }}">
			<div class="head">
				<div class="number-box">
					<span><img src="{{ event.logo_link }}" height="50px" width="50px" alt="logo"></span>
				</div>
				<h2><span class="small">{{ event.date }}</span>{{ event.name }}</h2>
			</div>
			<div class="body">
				<p>{{ event.short_des }}</p>
				<img src="{{ event.image_link }}" alt="Image for event">
			</div>
		</div>
        {% endfor %}
	</div>
</section>
    </div>
</div>






{% endblock body %}

BSA_WebSite/MainSite/templates/MainSite/gallery.html
{% extends 'base.html' %}
{% load static %}
{% block privatestyles %}
<link  href="https://unpkg.com/nanogallery2@2.2.0/dist/css/nanogallery2.min.css" rel="stylesheet" type="text/css">
<link href="{% static 'MainSite/navbar-side.css' %}" rel="stylesheet">
{% endblock privatestyles %}
{% block privatejs %}
<script  type="text/javascript" src="https://unpkg.com/nanogallery2@2.2.0/dist/jquery.nanogallery2.min.js"></script>
{% endblock privatejs %}
{% block body %}

<div class="navbar-inverse navbar-fixed-left">
  <ul class="nav navbar-nav">
   <li><a href="#showcase">ShowCase</a></li>
    {% for event in all_event_images %}
   <li><a href="#{{ event.event_name }}">{{ event.event_name }}</a></li>
    {% endfor %}
  </ul>
</div>

<div class="main">
    <div id="showcase" class="container event" style="min-height: 400px; background: #e7e7e7; margin-top: 2%">
        <h3> SHOWCASE </h3>
        <div id="nanogallery2" data-nanogallery2 = '{
                        "thumbnailHeight":  150,
                        "thumbnailWidth":   "auto",
                        "galleryDisplayMoreStep":   2,
                        "galleryDisplayMode":   "moreButton",
						"thumbnailDisplayTransition": "slideLeft",
                        "itemsBaseURL":     "{% static showcase.base_dir %}/"
                      }' >

                  <!-- gallery content -->
                  {% for name in showcase.images %}
                  <a href = "{{ name }}">Showcase {{ name }}</a>
                  {% endfor %}
        </div>
    </div>

    {% for event in all_event_images %}
	<div id='{{ event.event_name }}' class="container event" style="min-height: 400px; background: #e7e7e7; margin-top: 2%">
        <h3> {{ event.event_name }} </h3>
        <div id="nanogallery2 {{ event.event_name }}" data-nanogallery2 = '{
                        "thumbnailHeight":  150,
                        "thumbnailWidth":   "auto",
                        "galleryDisplayMoreStep":   2,
                        "galleryDisplayMode":   "moreButton",
						"thumbnailDisplayTransition":   "slideLeft",
                        "itemsBaseURL": "{% static event.base_dir %}/"
                      }' >

                  <!-- gallery content -->
                  {% for name in event.images %}
                  <a href = "{{ name }}">{{ event.event_name }} {{ name }}</a>
                  {% endfor %}
        </div>
    </div>
    {% endfor %}

</div>

{% endblock body %}

BSA_WebSite/MainSite/templates/MainSite/index.html
{% extends 'base.html' %}
{% load static %}
{% block privatestyles %}
    <link href="https://fonts.googleapis.com/css?family=Oswald:200,300,regular,500,600,700&subset=latin-ext,vietnamese,latin,cyrillic" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="{% static 'MainSite/scroll.css' %}" />
    <link rel="stylesheet" href="{% static 'MainSite/slider.css' %}" />
    <link rel="stylesheet" href="{% static 'MainSite/parallax.css' %}" />
    <link rel="stylesheet" href="{% static 'MainSite/animate.css' %}" />
{% endblock privatestyles %}
{% block privatejs %}
    <script src="{% static "MainSite/js/jssor.slider-27.1.0.min.js" %}" type="text/javascript"></script>
    <script src="{% static "MainSite/js/slider.js" %}" type="text/javascript"></script>
    <script src="{% static "MainSite/js/parallax.min.js" %}" type="text/javascript"></script>
    <script src="{% static "MainSite/js/wow.min.js" %}" type="text/javascript"></script>
{% endblock privatejs %}
{% block body %}

    <script>
    new WOW().init();
    </script>

<div id="jssor_1" style="position:relative;margin-left: 3%;margin-top: 1%; width:980px;height:380px;overflow:hidden;visibility:hidden; z-index: 1">
        <!-- Loading Screen -->
        <div data-u="loading" class="jssorl-009-spin" style="position:absolute;top:0px;left:0px;width:100%;height:100%;text-align:center;background-color:rgba(0,0,0,0.7);">
            <img style="margin-top:-19px;position:relative;top:50%;width:38px;height:38px;" src="img/spin.svg" />
        </div>
        <div data-u="slides" style="cursor:default;position:relative;top:0px;left:0px;width:980px;height:380px;overflow:hidden;">
            <div data-p="170.00">
                <img data-u="image" src="{% static 'MainSite/img_slideshow/001.jpg' %}" />
                <div data-u="caption" data-t="0" style="position:absolute;top:320px;left:30px;width:500px;height:40px;background-color:rgba(255,188,5,0.8);font-family:Oswald,sans-serif;font-size:32px;font-weight:200;line-height:1.2;text-align:center;">Mobile ready, touch swipe</div>
            </div>
            <div data-p="170.00">
                <img data-u="image" src="{% static 'MainSite/img_slideshow/002.jpg' %}" />
                <div data-u="caption" data-t="1" style="position:absolute;top:-50px;left:125px;width:500px;height:40px;background-color:rgba(255,188,5,0.8);font-family:Oswald,sans-serif;font-size:32px;font-weight:200;line-height:1.2;text-align:center;">Time lined layer animation</div>
            </div>
            <div data-p="170.00">
                <img data-u="image" src="{% static 'MainSite/img_slideshow/003.jpg' %}" />
                <div data-u="caption" data-t="2" style="position:absolute;top:30px;left:-505px;width:500px;height:40px;background-color:rgba(255,188,5,0.8);font-family:Oswald,sans-serif;font-size:32px;font-weight:200;line-height:1.2;text-align:center;">Finger catchable right to left</div>
            </div>
            <div data-p="170.00">
                <img data-u="image" src="{% static 'MainSite/img_slideshow/004.jpg' %}" />
                <div data-u="caption" data-t="3" style="position:absolute;top:30px;left:30px;width:500px;height:40px;background-color:rgba(255,188,5,0.8);font-family:Oswald,sans-serif;font-size:32px;font-weight:200;line-height:1.2;text-align:center;">responsive, scale smoothly</div>
            </div>
            <div data-p="170.00">
                <img data-u="image" src="{% static 'MainSite/img_slideshow/005.jpg' %}" />
                <div data-u="caption" data-t="4" style="position:absolute;top:30px;left:30px;width:500px;height:40px;background-color:rgba(255,188,5,0.8);font-family:Oswald,sans-serif;font-size:32px;font-weight:200;line-height:1.2;text-align:center;">image, text, and custom layers</div>
            </div>
            <div data-p="170.00">
                <img data-u="image" src="{% static 'MainSite/img_slideshow/006.jpg' %}" />
                <div data-u="caption" data-t="5" style="position:absolute;top:30px;left:600px;width:500px;height:40px;background-color:rgba(255,188,5,0.8);font-family:Oswald,sans-serif;font-size:32px;font-weight:200;line-height:1.2;text-align:center;">tons of transition type</div>
            </div>
            <div data-p="170.00">
                <img data-u="image" src="{% static 'MainSite/img_slideshow/007.jpg' %}" />
                <div data-u="caption" data-t="6" style="position:absolute;top:30px;left:30px;width:500px;height:40px;background-color:rgba(255,188,5,0.8);font-family:Oswald,sans-serif;font-size:32px;font-weight:200;line-height:1.2;text-align:center;">visual slider maker</div>
            </div>
            <div data-b="0" data-p="170.00">
                <img data-u="image" src="{% static 'MainSite/img_slideshow/008.jpg' %}" />
                <div data-u="caption" data-t="7" style="position:absolute;top:-50px;left:30px;width:500px;height:40px;background-color:rgba(255,188,5,0.8);font-family:Oswald,sans-serif;font-size:32px;font-weight:200;line-height:1.2;text-align:center;">play in and play out</div>
            </div>
            <div data-p="170.00">
                <img data-u="image" src="{% static 'MainSite/img_slideshow/009.jpg' %}" />
                <div data-u="caption" data-t="8" style="position:absolute;top:25px;left:150px;width:250px;height:250px;background-color:rgba(40,177,255,0.6);overflow:hidden;">
                    <div data-u="caption" data-t="9" style="position:absolute;top:100px;left:25px;width:200px;height:50px;font-family:Oswald,sans-serif;font-size:24px;font-weight:200;line-height:2.08;">A Child Layer</div>
                </div>
            </div>
            <div data-p="170.00">
                <img data-u="image" src="{% static 'MainSite/img_slideshow/010.jpg' %}" />
                <div data-u="caption" data-t="10" style="position:absolute;top:25px;left:100px;width:300px;height:260px;background-color:rgba(40,177,255,0.6);font-family:Oswald,sans-serif;font-size:24px;font-weight:200;line-height:1.25;padding:15px 15px 15px 15px;box-sizing:border-box;">This is full customized content layer.<br />​<br />

                    Everything is allowed.<br />​<br />You can insert

                    <a href="http://www.jssor.com">
                        a link
                    </a> or an image here.
                </div>
            </div>
        </div>
        <!-- Bullet Navigator -->
        <div data-u="navigator" class="jssorb052" style="position:absolute;bottom:12px;right:12px;" data-autocenter="1" data-scale="0.5" data-scale-bottom="0.75">
            <div data-u="prototype" class="i" style="width:16px;height:16px;">
                <svg viewbox="0 0 16000 16000" style="position:absolute;top:0;left:0;width:100%;height:100%;">
                    <circle class="b" cx="8000" cy="8000" r="5800"></circle>
                </svg>
            </div>
        </div>
        <!-- Arrow Navigator -->
        <div data-u="arrowleft" class="jssora053" style="width:55px;height:55px;top:0px;left:25px;" data-autocenter="2" data-scale="0.75" data-scale-left="0.75">
            <svg viewbox="0 0 16000 16000" style="position:absolute;top:0;left:0;width:100%;height:100%;">
                <polyline class="a" points="11040,1920 4960,8000 11040,14080 "></polyline>
            </svg>
        </div>
        <div data-u="arrowright" class="jssora053" style="width:55px;height:55px;top:0px;right:25px;" data-autocenter="2" data-scale="0.75" data-scale-right="0.75">
            <svg viewbox="0 0 16000 16000" style="position:absolute;top:0;left:0;width:100%;height:100%;">
                <polyline class="a" points="4960,1920 11040,8000 4960,14080 "></polyline>
            </svg>
        </div>
</div>

<div class="microsoft scrollcustom">
<p class="marquee" style="margin-top: 1%">
    <ul class="marquee">
        {% for announcement in announcements %}
            <li class="marquee"> {{ announcement.desc }}</li>
        {%  endfor %}
    </ul>
</p>
</div>

    <section style="margin-top: 2%">
        <div id="ios-notice" class="alert alert-info" style="display: none"><p><strong>Notice:</strong> Hello mobile user. Unfortunately, this parallax effect is not reliably achieved on mobile devices, so all you will see on this demo page are static backgrounds.  Please visit this page on a desktop browser to see its full effect.</p></div>
    </section>

<div style="position: relative; padding: 3%">
Hello World
</div>

<div class="parallax-container" data-parallax="scroll" data-position="top" data-image-src="{% static 'MainSite/img_parallax/stellar-spire-eagle-nebula-1400x900.jpg' %}" data-natural-width="1400" data-natural-height="900"></div>

    <div class="container wow fadeInLeft animated" style="min-height: 400px">
        <p style="font-size: x-large"> SOME STATIC INFO WITH SCROLL EFFECTS</p>
    </div>

<div class="parallax-container" data-parallax="scroll"data-speed="0.2" data-image-src="{% static 'MainSite/img_parallax/helix-nebula-1400x1400.jpg' %}" data-natural-width="1400" data-natural-height="1400"></div>

    <div class="container wow fadeInLeft animated" style="min-height: 400px">
        <p style="font-size: x-large"> SOME STATIC INFO WITH SCROLL EFFECTS</p>
    </div>

<div class="parallax-container" data-parallax="scroll" data-image-src="{% static 'MainSite/img_parallax/spiral-galaxy-1400x900.jpg' %}" data-natural-height="900"></div>

    <div class="container wow fadeInLeft animated" style="min-height: 400px">
        <p style="font-size: x-large"> SOME STATIC INFO WITH SCROLL EFFECTS</p>
    </div>

<div class="parallax-container" data-parallax="scroll" data-image-src="{% static 'MainSite/img_parallax/reflection-nebula-750x763.jpg' %}" data-natural-width="750" data-natural-height="763"></div>

    <div class="container wow fadeInLeft animated" style="min-height: 400px">
        <p style="font-size: x-large"> AND ON AND ON</p>
    </div>

<div class="parallax-container" data-parallax="scroll" data-position="top" data-image-src="{% static 'MainSite/img_parallax/stellar-spire-eagle-nebula-1400x900.jpg' %}" data-natural-width="1400" data-natural-height="900"></div>

    <script type="text/javascript">jssor_1_slider_init();</script>
    <script type="text/javascript">
    $(function(){
        if (navigator.userAgent.match(/(iPod|iPhone|iPad|Android)/)) {
          $('#ios-notice').style.display = "block";
          $('.parallax-container').height( $(window).height() * 0.5 | 0 );
        } else {
          $(window).resize(function(){
            var parallaxHeight = Math.max($(window).height() * 0.7, 200) | 0;
            $('.parallax-container').height(parallaxHeight);
          }).trigger('resize');
        }
      });
    </script>
{% endblock body %}

BSA_WebSite/MainSite/templates/MainSite/live.html
{% extends 'base.html' %}
{% load static %}
{% block body %}





{% endblock body %}

BSA_WebSite/MainSite/templates/base.html
{% load staticfiles %}
<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-COMPATIBLE" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title %}Board for Sports Activities - IIT Delhi{% endblock title %}</title>

    {% block stylesheets %}
    <link rel="stylesheet" href="{% static 'MainSite/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'MainSite/bootstrap-theme.min.css' %}" />
    <link rel="stylesheet" href="{% static 'MainSite/theme.css' %}" />

        {% block privatestyles %}
        {% endblock privatestyles %}
    {% endblock stylesheets %}

</head>
{% block scriptload %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
        {% block privatejs %}
        {% endblock privatejs %}

{% endblock scriptload %}

<body role="document" style="background: #c7ddef">

<nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <a href="{% url 'mainsite:index' %}" class="navbar-brand">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
          <a class="nav-link" href="{% url 'mainsite:people' %}">People</a>
      </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'mainsite:events' %}">Events</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'mainsite:gallery' %}">Gallery</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'mainsite:live' %}">LIVE</a>
        </li>
    </ul>
  </div>
</nav>
<br>

    {% if messages %}
<div class="container">
    <ul class="messages">
    {% for message in messages %}
    <li id="message_{{ forloop.counter }}"
        {% if message.tags %} class="alert alert-{{message.tags}}"{% endif %}>
        {{message}}
    </li>
    {% endfor %}
    </ul>
</div>
{% endif %}


    {% block body %}
    {% endblock body %}


<hr>
{% block footer %}
<div class="container marketing">
<footer>
    <p class="pull-right"><a href="#">Back to Top</a></p>
</footer>
</div>
{% endblock footer %}
</body>
</html>